overwrite: true
schema: "http://localhost:8000/___graphql"
config:
  namingConvention:
    enumValues: keep
generates:
  packages/gatsby-theme-recipe-organizer/src/graphql/types.ts:
    - "typescript"
